version: 0.2

phases:
  install:
    commands:
      - echo "Installing NGINX"
      - yum update -y
      - yum install -y nginx

  build:
    commands:
      - echo "Build started on $(date)"
      - mkdir -p /usr/share/nginx/html
      - cp index.html /usr/share/nginx/html/

  post_build:
    commands:
      - echo "Starting and enabling NGINX"
      - systemctl start nginx
      - systemctl enable nginx

artifacts:
  files:
    - '**/*'
